#!/usr/bin/env python3
"""Converts PNG textures to RGBA32 C arrays (u32 0xRRGGBBAA per texel), for mods: png2c.py <output .h> <png>...

Each texture is named after its file (e.g. gLinkAdultEyeOpenTex.rgba32.png -> gLinkAdultEyeOpenTex)."""

import struct
import sys
import zlib
from pathlib import Path

def read_png_rgba(path):
    data = Path(path).read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise SystemExit(f"{path}: not a PNG")
    pos = 8
    idat = b""
    palette = None
    trns = None
    while pos < len(data):
        length, kind = struct.unpack(">I4s", data[pos:pos + 8])
        chunk = data[pos + 8:pos + 8 + length]
        if kind == b"IHDR":
            width, height, depth, color, _, _, interlace = struct.unpack(">IIBBBBB", chunk)
        elif kind == b"PLTE":
            palette = [tuple(chunk[i:i + 3]) for i in range(0, len(chunk), 3)]
        elif kind == b"tRNS":
            trns = chunk
        elif kind == b"IDAT":
            idat += chunk
        pos += 12 + length
    if depth != 8 or interlace != 0 or color not in (2, 3, 6):
        raise SystemExit(f"{path}: unsupported PNG (8-bit RGB, RGBA or indexed only)")
    channels = {2: 3, 3: 1, 6: 4}[color]
    raw = zlib.decompress(idat)
    stride = width * channels
    rows = []
    prev = bytearray(stride)
    i = 0
    for _ in range(height):
        filt = raw[i]
        line = bytearray(raw[i + 1:i + 1 + stride])
        i += 1 + stride
        for x in range(stride):
            a = line[x - channels] if x >= channels else 0
            b = prev[x]
            c = prev[x - channels] if x >= channels else 0
            if filt == 1:
                line[x] = (line[x] + a) & 0xFF
            elif filt == 2:
                line[x] = (line[x] + b) & 0xFF
            elif filt == 3:
                line[x] = (line[x] + ((a + b) >> 1)) & 0xFF
            elif filt == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                line[x] = (line[x] + (a if pa <= pb and pa <= pc else b if pb <= pc else c)) & 0xFF
        rows.append(line)
        prev = line
    texels = []
    for line in rows:
        for x in range(width):
            px = line[x * channels:(x + 1) * channels]
            if color == 6:
                texels.append(tuple(px))
            elif color == 2:
                texels.append((px[0], px[1], px[2], 255))
            else:
                r, g, b = palette[px[0]]
                alpha = trns[px[0]] if trns is not None and px[0] < len(trns) else 255
                texels.append((r, g, b, alpha))
    return width, height, texels

def main():
    if len(sys.argv) < 3:
        raise SystemExit(__doc__)
    out = ["// Generated by mods/sdk/png2c.py, do not edit", ""]
    for png in sys.argv[2:]:
        name = Path(png).name.split(".")[0]
        width, height, texels = read_png_rgba(png)
        out.append(f"// {Path(png).name}: {width}x{height}")
        out.append(f"static u32 {name}[{width * height}] = {{")
        for row in range(height):
            vals = texels[row * width:(row + 1) * width]
            out.append("    " + ", ".join(f"0x{r:02X}{g:02X}{b:02X}{a:02X}" for r, g, b, a in vals) + ",")
        out.append("};")
        out.append("")
    Path(sys.argv[1]).write_text("\n".join(out))

if __name__ == "__main__":
    main()
