#!/usr/bin/env python3
"""
Generate patches/sot_skelanime.c: the decomp's skeleton draw functions (z_skelanime.c), with each limb drawn in its
own RT64 matrix group (and the post-limb draw in another one), so that the limbs are interpolated separately.

    python3 tools/gen_skelanime_patches.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "lib" / "oot-decomp" / "src" / "code" / "z_skelanime.c"
OUT = ROOT / "patches" / "sot_skelanime.c"

FUNCS = [
    "SkelAnime_DrawLimbLod", "SkelAnime_DrawLod", "SkelAnime_DrawFlexLimbLod", "SkelAnime_DrawFlexLod",
    "SkelAnime_DrawLimbOpa", "SkelAnime_DrawOpa", "SkelAnime_DrawFlexLimbOpa", "SkelAnime_DrawFlexOpa",
    "SkelAnime_DrawLimb", "SkelAnime_Draw", "SkelAnime_DrawFlexLimb", "SkelAnime_DrawFlex",
]


def extract(lines, name):
    start = next(i for i, l in enumerate(lines) if re.match(rf"^(void|Gfx\*) {name}\(", l))
    end = next(i for i in range(start, len(lines)) if lines[i] == "}")
    return lines[start:end + 1]


def transform(body):
    header = body[0]
    gfx_list = "gfx" if header.startswith("Gfx*") else "play->state.gfxCtx->polyOpa.p"
    out = []
    i = 0
    while i < len(body):
        line = body[i]
        if "(overrideLimbDraw == NULL) || !overrideLimbDraw(play, " in line:
            index = "1" if "overrideLimbDraw(play, 1," in line else "limbIndex"
            indent = line[: len(line) - len(line.lstrip())]
            out.append(f"{indent}// @recomp Draw the limb in its own matrix group.")
            out.append(f"{indent}{gfx_list} = sot_push_limb_group({gfx_list}, arg, {index}, false);")
            out.append(line)
        elif line.strip() == "if (postLimbDraw != NULL) {":
            indent = line[: len(line) - len(line.lstrip())]
            index = "1" if any("overrideLimbDraw(play, 1," in l for l in body) else "limbIndex"
            out.append(f"{indent}// @recomp Pop the limb's matrix group, and draw the post-limb draw in its own one.")
            out.append(f"{indent}{gfx_list} = sot_pop_group({gfx_list}, arg);")
            out.append(f"{indent}{gfx_list} = sot_push_limb_group({gfx_list}, arg, {index}, true);")
            out.append(line)
            # Copy the block up to its closing brace
            i += 1
            while body[i] != indent + "}":
                out.append(body[i])
                i += 1
            out.append(body[i])
            out.append(f"{indent}{gfx_list} = sot_pop_group({gfx_list}, arg);")
        else:
            out.append(line)
        i += 1
    out[0] = "RECOMP_PATCH " + out[0]
    return out


def main():
    lines = SRC.read_text().splitlines()
    result = [
        "// Generated by tools/gen_skelanime_patches.py from the decomp's z_skelanime.c: the skeleton draw functions,",
        "// with each limb in its own RT64 matrix group so that limbs are interpolated separately (high framerates).",
        "",
        '#include "patches.h"',
        '#include "sot_interpolation.h"',
        "",
    ]
    for name in FUNCS:
        result += transform(extract(lines, name))
        result.append("")
    OUT.write_text("\n".join(result))
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
